name: Benchmarks
on:
  - push
  - pull_request

jobs:
  benchmark_next:
    name: benchmark next

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.base_ref }}

      - name: Setup Node
        uses: actions/setup-node@v3.5.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Modules
        run: npm i
      - name: Run Benchmark
        run: npm run bench

      - name: Run Benchmark Resource Usage
        run: npm run bench:resourceUsage

  benchmark_branch:
    name: benchmark branch

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      - name: Setup Node
        uses: actions/setup-node@v3.5.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Modules
        run: npm i

      - name: Run Benchmark
        run: npm run bench

      - name: Run Benchmark Resource Usage
        run: npm run bench:resourceUsage
