name: Benchmarks
on:
  - push
  - pull_request

jobs:
  benchmark_next:
    name: benchmark next

    strategy:
      matrix:
        node-version: [20.x]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.base_ref }}

      - name: Setup Node
        uses: actions/setup-node@v4.0.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Modules
        run: npm i
      - name: Run Benchmark
        run: npm run bench

      - name: Run Benchmark Resource Usage
        run: npm run bench:resourceUsage

  benchmark_branch:
    name: benchmark branch

    strategy:
      matrix:
        node-version: [20.x]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1

      - name: Setup Node
        uses: actions/setup-node@v4.0.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Modules
        run: npm i

      - name: Run Benchmark
        run: npm run bench

      - name: Run Benchmark Resource Usage
        run: npm run bench:resourceUsage
